name: cmdr
description: Dart package that provides a lightweight implementation of the Mediator pattern tailored for Command Query Responsibility Segregation (CQRS) applications.

version: 1.0.1
homepage: https://github.com/IldySilva/cmdr
repository: https://github.com/IldySilva/cmdr.git
issue_tracker: https://github.com/IldySilva/cmdr/issues

topics:
  - cqrs
  - mediator
  - mediatr
  - command
  - query
  


environment:
  sdk: ^3.3.0



dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
