name: cmdr
description: Dart package that provides a lightweight implementation of the Mediator pattern tailored for Command Query Responsibility Segregation (CQRS) applications.

version: 1.0.0
homepage: https://github.com/IldySilva/cmdr
repository: https://github.com/IldySilva/cmdr.git
issue_tracker: https://github.com/IldySilva/cmdr/issues

topics:
  - CQRS
  - Mediator Pattern
  - Mediatr
  - Command
  - Query
  


environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
